export enum ActionType {

  //flags
  CLOSE_INTER_AD = "CLOSE_INTER_AD",
  SHOW_INTER_AD = "SHOW_INTER_AD",
  GET_PRODUCTS = "GET_PRODUCTS",
  REMOVE_ADS = "REMOVE_ADS",

   //auth
   USER_LOADING = "USER_LOADING",
   USER_LOADED = "USER_LOADED",
   LOGIN_FAILED = "LOGIN_FAILED",
   LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
   LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL",
   AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
   AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED",
   AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS",
   AUTO_LOGIN = "AUTO_LOGIN",
   USERNAME_SUCCESS = "USERNAME_SUCCESS",
   PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",

   //session
   CREATE_SESSION ="CREATE_SESSION",
   CREATE_JOURNAL = "CREATE_JOURNAL",
   START_SESSION = "START_SESSION",
}
